repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: python -m ruff check --fix
        language: system
        pass_filenames: true
        require_serial: true
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: python -m ruff format
        language: system
        pass_filenames: true
        require_serial: true
        types_or: [python, pyi]
